# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 06:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170625_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 6, 27, 6, 47, 8, 310974, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
